// flow-typed signature: 84c7441f4c1aa855f7484531e53a9a17
// flow-typed version: <<STUB>>/styled-jss_v^0.3.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-jss/lib/index' {
  declare module.exports: any;
}

declare module 'styled-jss/lib/utils/filter-props' {
  declare module.exports: any;
}

declare module 'styled-jss/src/index' {
  declare module.exports: any;
}

declare module 'styled-jss/src/tests/App' {
  declare module.exports: any;
}

declare module 'styled-jss/src/tests/index.spec' {
  declare module.exports: any;
}

declare module 'styled-jss/src/utils/filter-props' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-jss/lib/index.js' {
  declare module.exports: $Exports<'styled-jss/lib/index'>;
}
declare module 'styled-jss/lib/utils/filter-props.js' {
  declare module.exports: $Exports<'styled-jss/lib/utils/filter-props'>;
}
declare module 'styled-jss/src/index.js' {
  declare module.exports: $Exports<'styled-jss/src/index'>;
}
declare module 'styled-jss/src/tests/App.jsx' {
  declare module.exports: $Exports<'styled-jss/src/tests/App'>;
}
declare module 'styled-jss/src/tests/index.spec.jsx' {
  declare module.exports: $Exports<'styled-jss/src/tests/index.spec'>;
}
declare module 'styled-jss/src/utils/filter-props.js' {
  declare module.exports: $Exports<'styled-jss/src/utils/filter-props'>;
}
